import type { Metadata } from "next";
import "../style/globals.css";
import { MainNav } from "@/components/main-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="w-screen">
          <div>
            <MainNav />
          </div>
          <div className="relative w-full mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
